package scheduler.tests;

import static org.junit.Assert.*;
import org.junit.Test;
import scheduler.model.Booking;
import scheduler.model.BookingFactory;
import scheduler.strategy.StudentPricingStrategy;
import scheduler.strategy.FacultyPricingStrategy;
import scheduler.strategy.PricingStrategy;

public class BookingFactoryTest {

    @Test
    public void testCreateBookingAutoGeneratedId() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking("R101", "U101", 9, 11, strategy);
        
        assertNotNull(booking);
        assertNotNull(booking.getId());
        assertTrue(booking.getId().startsWith("b-"));
        assertEquals("R101", booking.getRoomId());
        assertEquals("U101", booking.getUserId());
        assertEquals(9, booking.getStartHour());
        assertEquals(11, booking.getEndHour());
    }

    @Test
    public void testCreateBookingCustomId() {
        PricingStrategy strategy = new FacultyPricingStrategy();
        Booking booking = BookingFactory.createBooking("CUSTOM_01", "R102", "U102", 10, 12, strategy);
        
        assertNotNull(booking);
        assertEquals("CUSTOM_01", booking.getId());
        assertEquals("R102", booking.getRoomId());
        assertEquals("U102", booking.getUserId());
        assertEquals(10, booking.getStartHour());
        assertEquals(12, booking.getEndHour());
    }

    @Test
    public void testUniqueIdsGeneratedForMultipleCalls() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking b1 = BookingFactory.createBooking("R101", "U101", 9, 10, strategy);
        Booking b2 = BookingFactory.createBooking("R101", "U101", 9, 10, strategy);
        
        assertNotEquals(b1.getId(), b2.getId());
    }

    @Test
    public void testCreateBookingWithNullStrategy() {
        Booking booking = BookingFactory.createBooking("R101", "U101", 9, 11, null);
        assertNotNull(booking);
    }

    @Test
    public void testCreateBookingSingleHourSpan() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking("R105", "U103", 14, 15, strategy);
        assertEquals(1, booking.getEndHour() - booking.getStartHour());
    }

    @Test
    public void testCreateBookingWithNullRoomOrUserId() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking(null, null, 8, 10, strategy);
        assertNull(booking.getRoomId());
        assertNull(booking.getUserId());
    }

    @Test
    public void testCreateBookingCustomIdWithNulls() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking("ID_999", null, null, 12, 13, strategy);
        assertEquals("ID_999", booking.getId());
    }

    @Test
    public void testCreatedBookingCalculatesCostCorrectly() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking("R101", "U101", 9, 11, strategy);
        assertEquals(strategy.calculateCost(2), booking.calculateTotalCost(), 0.001);
    }

    @Test
    public void testCreatedBookingReflectsDeposit() {
        PricingStrategy strategy = new FacultyPricingStrategy();
        Booking booking = BookingFactory.createBooking("R101", "U102", 9, 11, strategy);
        assertEquals(strategy.getHourlyRate(), booking.getUpfrontDeposit(), 0.001);
    }

    @Test
    public void testCreatedBookingToStringFormat() {
        PricingStrategy strategy = new StudentPricingStrategy();
        Booking booking = BookingFactory.createBooking("FIXED_ID", "R101", "U101", 9, 11, strategy);
        assertEquals("Booking[FIXED_ID room=R101 user=U101 9-11]", booking.toString());
    }
}